### ISSUE TITLE
Plugin failed to load

### ISSUE THREAD

**Issue by rdomingue** [blainesch/zazu-weather#2]
Plugin failed to load
{
  "block": "DefaultWeather",
  "error": "{ Error: Cannot find module 'weather-js'\n    at Module._resolveFilename (module.js:455:15)\n    at Function.Module._resolveFilename (C:\\Users\\rene.domingue\\AppData\\Local\\Programs\\zazu\\resources\\electron.asar\\common\\reset-search-paths.js:35:12)\n    at Function.Module._load (module.js:403:25)\n    at Module.require (module.js:483:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:/Users/rene.domingue/.zazu/plugins/blainesch/zazu-weather/weather.js:1:25)\n    at Module._compile (module.js:556:32)\n    at loader (C:\\Users\\rene.domingue\\AppData\\Local\\Programs\\zazu\\resources\\app.asar\\node_modules\\babel-register\\lib\\node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .js] (C:\\Users\\rene.domingue\\AppData\\Local\\Programs\\zazu\\resources\\app.asar\\node_modules\\babel-register\\lib\\node.js:154:7)\n    at Module.load (module.js:473:32) code: 'MODULE_NOT_FOUND' }",
  "level": "error",
  "message": "Plugin failed to load",
  "plugin": "blainesch/zazu-weather",
  "time": "2017-04-05T14:22:47.761Z"
}

**Comment by bayleedev** [comment]
What version of zazu are you using? Thank you for reporting!

**Comment by rdomingue** [comment]
App Environment: production
App Version: 0.5.2
Electron Version: 1.3.14
Node Version: 6.5.0
Chrome Version: 52.0.2743.82

**Comment by bayleedev** [comment]
Is it possible you installed the plugin with a different version of zazu?

Can you try deleteing `C:\Users\rene.domingue\.zazu` folder and trying again?

**Comment by rdomingue** [comment]
I don't have any other version, first time I've download it and try it.
But I tried this anyway and get the same issue. In fact, it's really unstable. I got errors with clipboard that can't update, errors with weather... etc.. sometimes weather seems to work.. but other times it doesn't

**Comment by marksev1** [comment]
For me it also doesnt work (on Ubuntu 16.04), would be awesome to have it tho'

**Comment by Koolstr** [comment]
I had the same issue. Deleting the .zazu folder fixed it though.
